# Generated by Django 4.2.3 on 2023-07-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_userprofile_options_alter_userprofile_managers_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="photo",
            new_name="image",
        ),
    ]
