# Generated by Django 4.2.3 on 2023-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portrait", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portrait",
            name="photo",
            field=models.URLField(),
        ),
    ]
