# Generated by Django 4.2.3 on 2023-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portrait", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portrait",
            name="photo",
            field=models.ImageField(default=1, upload_to="Media/Portrait_photos"),
            preserve_default=False,
        ),
    ]
