# Generated by Django 4.2.3 on 2023-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portrait", "0002_portrait_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portrait",
            name="photo",
            field=models.ImageField(upload_to="Portrait_photos"),
        ),
    ]
