# Generated by Django 4.2.3 on 2023-07-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portrait", "0003_alter_portrait_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="portrait",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
